# Development Environment

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/pappapp
spring.datasource.username=postgres
spring.datasource.password=postgres

# Frontend URL Configuration
app.frontend.url=http://localhost:3000
app.frontend.reset-password.path=/authentication?mode=reset-password

# Development specific settings
logging.level.com.pappgroup.pappapp=DEBUG
spring.jpa.show-sql=true